### ISSUE TITLE
Sidebar: 'imu' npm module[Unrelated to Project]

### ISSUE THREAD

**Issue by seflless** [thomas-jeepe/redux-chaos#2]
hi @thomas-jeepe. Sorry to use an issue on this project to start a conversation. Your email wasn't listed or any other contact information. I was wondering if you'd free up the **imu** npm module. I wanted to make an IMU simulator that makes it easy for people to attach a phone to hardware devices and have access to compass, gyro, accelerometer, and any other sensor information.

No worries if it's a no, just saw that you aren't using it and the related repo is gone. My npm handle is **francoislaberge**

Thanks in advance,
Francois

**Comment by seflless** [comment]
My email is francoislaberge@gmail.com if you want to have a private conversation. Or [@francoislaberge](twitter.com/francoislaberge) on twitter if you want to dm.

**Comment by thomas-jeepe** [comment]
Gave you owner access and removed myself, didn't need it anymore.

Sorry about making you wait I completely forgot about your email.
